server:
  port: 8080

spring:
  application:
    name: database-speed-test

  datasource:
    url: jdbc:postgresql://localhost:5432/database_speed_test
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

    hikari:
      pool-name: JpaExampleHikariPool
      maximum-pool-size: 20
      minimum-idle: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      auto-commit: false
      data-source-properties:
        reWriteBatchedInserts: true
        prepareThreshold: 1

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        connection:
          provider_disables_autocommit: true

logging:
  level:
    #org.hibernate.SQL: debug
    #org.hibernate.orm.jdbc.bind: trace
    #org.postgresql.core: TRACE
    com.zaxxer.hikari: info
    x: trace
    #org.springframework.jdbc.core.JdbcTemplate: DEBUG
    #org.springframework.jdbc.core.StatementCreatorUtils: TRACE

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
